# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: alessiodionisi/setup-age-action@v1.3.0
      - run: |
          echo <<-'EOF'  | age -R "${{ secrets.AGE_KEY}} > secrets.txt.age
            AZURE_USETHESOURCE_PAT="${{ secrets.AZURE_USETHESOURCE_PAT }}"
          EOF 
      - uses: actions/upload-artifact@v4
        with:
          path: "secrets.txt.age"
        

